#!/bin/bash

session=cpp-playground
tmux new-session -d -s $session
tmux send-keys -t $session:1 'vi -S Session.vim' C-m
tmux split -h -t $session:1
tmux send-keys -t $session:1 'cd build' C-m

tmux attach-session -t $session

